### ISSUE TITLE
Rubocopの導入&指摘解消

### ISSUE THREAD

**Issue by takahiromasui001** [ChisatoMatoba/odekake-with-dogs#6]
rubocop.ymlはこれで
```
require:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-fjord:
    - "config/rubocop.yml"
    - "config/rails.yml"

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/PerceivedComplexity:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/system/*

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
```
